### ISSUE TITLE
ALT-tabbing and returning to the game makes the game renderer freeze

### ISSUE THREAD

**Issue by msimic** [mmdanggg2/D3D9DrvRTX#5]
Audio continues to play but the game is frozen on the last rendered screen and can be only closed from windows.

**Comment by mmdanggg2** [comment]
Freezing should be fixed with 6d39a30362af473ac298222e9bfa3c93e46b5008.
Tracking some other issues with the fullscreening with remix itself here: https://github.com/NVIDIAGameWorks/rtx-remix/issues/591 but that's on remix so I'm gonna close this for now. Next release with that fixed should be out soon-ish.
